- name: Install system packages (dnf)
  dnf:
    name: ['vim-enhanced', 'python2-pip', 'python3-pip', 'gcc', 'make', 'binutils', 'ack']
    state: latest
  when: vars.ansible_facts.pkg_mgr == 'dnf'
  tags:
    - vim

- name: Install system packages (yum)
  yum:
    name: ['vim-enhanced', 'python2-pip', 'python3-pip', 'gcc', 'make', 'binutils', 'ack']
    state: latest
  when: vars.ansible_facts.pkg_mgr == 'yum'
  tags:
    - vim

- name: Install system packages (apt)
  apt:
    name: ['vim', 'python-pip-whl', 'python3-pip', 'gcc', 'make', 'binutils', 'ack']
    state: latest
  when: vars.ansible_facts.pkg_mgr == 'apt'
  tags:
    - vim

- name: Install python packages (pip)
  pip:
    name: ['pyflakes', 'pep8', 'pylint', 'ipython']
  tags:
    - vim

- name: Stat homedirs
  stat:
    path: "{{ item.homedir }}"
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.homedir }}"
  register: reg_stat_perms
  tags:
    - vim

- name: Install Vundle
  git:
    repo: https://github.com/gmarik/Vundle.vim.git
    dest: "{{ item.0.homedir }}/.vim/bundle/Vundle.vim"
  with_together:
    - "{{ users }}"
    - "{{ reg_stat_perms.results }}"
  when: item.1.stat.exists
  loop_control:
    label: "{{ item.0.homedir }}"
  tags:
    - vim

- name: Install vimrc
  template:
    src: .vimrc.j2
    dest: "{{ item.0.homedir }}/.vimrc"
  with_together:
    - "{{ users }}"
    - "{{ reg_stat_perms.results }}"
  when: item.1.stat.exists
  loop_control:
    label: "{{ item.0.homedir }}"
  tags:
    - vim

- name: Set perms
  file:
    path: "{{ item.0.homedir }}/.vimrc"
    owner: "{{ item.0.name }}"
    group: "{{ item.0.name }}"
    mode: '0644'
  with_together:
    - "{{ users }}"
    - "{{ reg_stat_perms.results }}"
  when: item.1.stat.exists
  loop_control:
    label: "{{ item.0.homedir }}"
  tags:
    - vim

- name: Vim | Set perms for .vim
  file:
    path: "{{ item.homedir }}/.vim"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    recurse: yes
  with_items:
    - "{{ users }}"
  loop_control:
    label: "{{ item.homedir }}"
  tags:
    - vim

- debug:
    msg: Run ':PluginInstall' vim command manually to install plugins
  tags:
    - vim

