- name: Install packages (dnf)
  become: true
  dnf:
    name: ['tilix']
    state: latest
  when: vars.ansible_facts.pkg_mgr == 'dnf'
  tags:
    - tilix

- name: Install packages (yum)
  become: true
  yum:
    name: ['tilix']
    state: latest
  when: vars.ansible_facts.pkg_mgr == 'yum'
  tags:
    - tilix

- name: Install packages (apt)
  become: true
  apt:
    name: ['tilix']
    state: latest
  when: vars.ansible_facts.pkg_mgr == 'apt'
  tags:
    - tilix

- name: Restore config
  #become_user: user
  shell: |
    dconf load /com/gexperts/Tilix/ < {{ role_path}}/files/tilix.dconf
  tags:
    - tilix

