---
- hosts: localhost
  #gather_facts: yes
  #become: true
  vars:
    users:
      - name: 'root'
        homedir: '/root'
        ps1: "export PS1='\\[\\033[01;31m\\]#\\[\\033[00m\\] '" # red #
      - name: 'gcf89'
        homedir: '/home/gcf89'
        ps1: "export PS1='\\[\\033[01;32m\\]$\\[\\033[00m\\] '" # green $
        #- name: 'pahomov'
        #- homedir: '/home/pahomov'
        #- ps1: "export PS1='\\[\\033[01;32m\\]$\\[\\033[00m\\] '" # green $
    git:
      #TODO: To hide sensitive data use ansible vault
      email: "sergey.pakhomov.89@gmail.com"
      name: "Sergey Pakhomov"
  roles:
    - bash
    - git
    - vim
    - tmux
    #- tilix
    #- screen
    #- mate
