- name: Install packages (dnf)
  dnf:
    name: ['git']
    state: latest
  when: vars.ansible_facts.pkg_mgr == 'dnf'
  tags:
    - git

- name: Install packages (yum)
  yum:
    name: ['git']
    state: latest
  when: vars.ansible_facts.pkg_mgr == 'yum'
  tags:
    - git

- name: Install packages (apt)
  apt:
    name: ['git']
    state: latest
  when: vars.ansible_facts.pkg_mgr == 'apt'
  tags:
    - git

- name: Install gitconfig
  template:
    src: .gitconfig.j2
    dest: "{{ item.homedir }}/.gitconfig"
  with_items: "{{ users }}"
  tags:
    - git

- name: Set perms
  file:
    path: "{{ item.homedir }}/.gitconfig"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0644'
  with_items: "{{ users }}"
  tags:
    - git
