- name: Install packages (dnf)
  dnf:
    name: ['tmux', 'xsel', 'xclip']
    state: latest
  when: vars.ansible_facts.pkg_mgr == 'dnf'
  tags:
    - tmux

- name: Install packages (yum)
  yum:
    name: ['tmux', 'xsel', 'xclip']
    state: latest
  when: vars.ansible_facts.pkg_mgr == 'yum'
  tags:
    - tmux

- name: Install packages (apt)
  apt:
    name: ['tmux', 'xsel', 'xclip']
    state: latest
  when: vars.ansible_facts.pkg_mgr == 'apt'
  tags:
    - tmux

- name: Install tmux.conf
  template:
    src: .tmux.conf.j2
    dest: "{{ item.homedir }}/.tmux.conf"
  with_items: "{{ users }}"
  tags:
    - tmux

- name: Set perms
  file:
    path: "{{ item.homedir }}/.tmux.conf"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0644'
  with_items: "{{ users }}"
  tags:
    - tmux

      #- name: Create bin dir
      #  file:
      #    path: "{{ item.homedir }}/bin"
      #    owner: "{{ item.name }}"
      #    group: "{{ item.name }}"
      #    mode: '0644'
      #    state: directory
      #  with_items: "{{ users }}"
      #  tags:
      #    - tmux

- name: Copy show-stats.sh
  copy:
    src: show-stats.sh
    #dest: "{{ item.homedir }}/bin"
    dest: "/usr/local/bin"
    mode: '0755'
    owner: root
    group: root
    #with_items: "{{ users }}"
  tags:
    - tmux
